const express = require("express");
const ConsultantRouter = require("./consultant_router");
const IntrestRouter = require("./intrested_router");
const PropertyTypeRouter = require("./property_type_router");
const PropertyStatusRouter = require("./property_status_router");
const FooterContactDetailsRouter = require("./footer_contact_details");
const PropertyRouter = require("./property_router");
const AboutUsRouter = require("./about_us_router");
const BlogCategoryRouter = require("./blog_category_router");
const BlogRouter = require("./blog_router");
const TestimonialRouter = require("./testimonial_router");
const WhyChoseRouter = require("./why_chose_router");
const DeveloperRouter = require("./developers_routes");
const CommunitiesRouter = require("./communities_routes");
const BannerRouter = require("./banner_router");
const FaqRouter = require("./faq_router");
const ServieRouter = require("./service_router");
const QueryRouter = require("./query_from_router");
const ValuationRouter = require("./valuation_router");
const preBookRouter = require("./pre_book_router");
const InquiryRoutes = require("./sell_inquiry_router");
const DownloadRouter = require("./download_router");
const JobRouter = require("./job_router");
const jobFormRouter = require("./job_form_router");
const TeamRouter = require("./team_router");
const ServicesPageRouter = require("./ServicesPage_router");
const ContactQueryRouter = require("./conact_query_router");

const Router = express();

Router.use("/property", PropertyRouter);
Router.use("/consultant", ConsultantRouter);
Router.use("/banner", BannerRouter);
Router.use("/intrest", IntrestRouter);
Router.use("/property-status", PropertyStatusRouter);
Router.use("/developer", DeveloperRouter);
Router.use("/communities", CommunitiesRouter);
Router.use("/property-type", PropertyTypeRouter);
Router.use("/about-us", AboutUsRouter);
Router.use("/blog-category", BlogCategoryRouter);
Router.use("/blog", BlogRouter);
Router.use("/testimonial", TestimonialRouter);
Router.use("/why-chose", WhyChoseRouter);
Router.use("/faqs", FaqRouter);
Router.use("/jobs", JobRouter);
Router.use("/jobForm", jobFormRouter);
Router.use("/team", TeamRouter);
Router.use("/queries", QueryRouter);
Router.use("/contactQueries", ContactQueryRouter);
Router.use("/services", ServieRouter);
Router.use("/service", ServicesPageRouter);
Router.use("/valuation", ValuationRouter);
Router.use("/inquiry", InquiryRoutes);
Router.use("/pre-book", preBookRouter);
Router.use("/footer-contact", FooterContactDetailsRouter);
Router.use("/brochure", DownloadRouter);

module.exports = Router;
